myapp/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # path("", views.redirect_to_login, name="redirect_to_login"),
    path("login/", views.login_view, name="login"),
    path("", views.home, name="home"),
    path("service_page/", views.service_page, name="service_page"),
    path("vehicles/", views.vehicles, name="vehicles"),
    path("vehicles/register", views.register_vehicle, name="register_vehicle"),
    path("vehicles/assign", views.assign_vehicle, name="assign_vehicle"),
    path('vehicles/delete/<int:vehicle_id>/', views.delete_vehicle, name='delete_vehicle'),
    path("personnel/", views.personnel, name="personnel"),
    path("contacts/", views.contacts, name="contacts"),
    path("about_us/", views.about_us, name="about_us"),
    path("make_an_appointment/", views.make_an_appointment, name="make_an_appointment"),
    path("logout/", views.logout_view, name="logout"),
    path('personnel/select_role/', views.select_role, name='select_role'),
    path('personnel/register/', views.register_personnel, name='register_personnel'),
    path('personnel/delete/<int:user_id>/', views.delete_personnel, name='delete_personnel'),
    path('personnel/search/', views.search_personnel, name='search_personnel'),
    path('create_task/', views.create_task, name='create_task'),
]

swe/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("myapp.urls")),
    path("admin/", admin.site.urls),
]

myapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin, Group, Permission

class UserManager(BaseUserManager):
    use_in_migrations = True

    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(email, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    role = models.CharField(max_length=50)      # 'Driver', 'Maintenance', 'Admin', 'FuelingPerson'
    phone_number = models.CharField(max_length=20, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()
    groups = models.ManyToManyField(
        Group,
        related_name="custom_user_set",
        blank=True,
    )
    user_permissions = models.ManyToManyField(
        Permission,
        related_name="custom_user_set",
        blank=True,
    )
class Vehicle(models.Model):
    make = models.CharField(max_length=50)
    model = models.CharField(max_length=50)
    year = models.IntegerField()
    license_plate = models.CharField(max_length=20)
    type = models.CharField(max_length=50)
    sitting_capacity = models.IntegerField()
    status = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.id}'

class Driver(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    vehicle = models.OneToOneField(Vehicle, on_delete=models.SET_NULL, null=True)
    driving_license = models.CharField(max_length=50, unique=True, null=True)

    def __str__(self):
        return f'{self.user.id}'

class Admin(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

class MaintenancePersonnel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

class FuelingPerson(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    gas_station_name = models.CharField(max_length=50)

class MaintenanceRecord(models.Model):
    vehicle = models.ForeignKey(Vehicle, on_delete=models.SET_NULL, null=True)
    maintenance_user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    service_type = models.CharField(max_length=50)
    date = models.DateField()
    cost = models.DecimalField(max_digits=10, decimal_places=2)

class FuelRecord(models.Model):
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    driver_user = models.ForeignKey(User, on_delete=models.CASCADE)
    fuel_date = models.DateField()
    amount_of_fuel = models.DecimalField(max_digits=10, decimal_places=2)
    total_cost = models.DecimalField(max_digits=10, decimal_places=2)
    gas_station_name = models.CharField(max_length=50)
    fueling_person = models.ForeignKey(FuelingPerson, on_delete=models.SET_NULL, null=True, blank=True, related_name='fuel_records')

class Route(models.Model):
    driver_user = models.ForeignKey(User, on_delete=models.CASCADE)
    start_location = models.CharField(max_length=100)
    end_location = models.CharField(max_length=100)
    task_name = models.CharField(max_length=50, null=True)
    status = models.CharField(max_length=50)

myapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .forms import (
    CustomAuthenticationForm,
    BaseUserRegistrationForm,
    AdminRegistrationForm,
    DriverRegistrationForm,
    MaintenancePersonnelRegistrationForm,
    FuelingPersonRegistrationForm
)
from django.contrib.auth import login, authenticate
from django.contrib.auth import authenticate, login as auth_login  # ensure correct import
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout


def login_view(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(data=request.POST)
        if form.is_valid():
            user = authenticate(username=form.cleaned_data['username'],
                                password=form.cleaned_data['password'])
            if user is not None:
                login(request, user)
                next_url = request.POST.get('next') or request.GET.get('next')
                print(next_url)
                if next_url:
                    return redirect(next_url)
                return redirect('home')  # Replace with your home view's URL name
    else:
        form = CustomAuthenticationForm()
    return render(request, 'myapp/login.html', {'form': form})

@login_required
def home(request):
    return render(request, "myapp/home.html", {})

@login_required
def service_page(request):
    return render(request, "myapp/service_page.html", {})

@login_required
def vehicles(request):
    return render(request, "myapp/vehicles.html", {})

@login_required
def personnel(request):
    selected_role = request.GET.get('role')
    personnel_data = None

    if selected_role == 'Driver':
        personnel_data = Driver.objects.select_related('user').all()
    elif selected_role == 'Maintenance':
        personnel_data = MaintenancePersonnel.objects.select_related('user').all()
    elif selected_role == 'FuelingPerson':
        personnel_data = FuelingPerson.objects.select_related('user').all()

    return render(request, 'myapp/personnel.html', {'personnel_data': personnel_data, 'selected_role': selected_role})

@login_required
def contacts(request):
    return render(request, "myapp/contacts.html", {})

@login_required
def about_us(request):
    return render(request, "myapp/about_us.html", {})

@login_required
def make_an_appointment(request):
    return render(request, "myapp/appointment.html", {})

@login_required
def logout_view(request):
    logout(request)
    return redirect('../login')

from django.shortcuts import render, redirect
from .forms import (BaseUserRegistrationForm, DriverRegistrationForm, 
                    AdminRegistrationForm, MaintenancePersonnelRegistrationForm, 
                    FuelingPersonRegistrationForm, VehicleRegistrationForm, VehicleAssignmentForm, TaskCreationForm)
from .models import User, Driver, Admin, MaintenancePersonnel, FuelingPerson, Vehicle

from django.shortcuts import render

def select_role(request):
    return render(request, 'myapp/select_role.html')

def register_personnel(request):
    # Get the role from the URL parameter
    selected_role = request.GET.get('role')
    # Choose the appropriate form based on the selected role
    form_class = get_form_class_for_role(selected_role)

    if request.method == 'POST':
        form = form_class(request.POST)
        if form.is_valid():
            # Create the User instance
            new_user = form.save(commit=False)
            new_user.role = selected_role
            new_user.save()

            # Create the role-specific profile
            create_related_profile(new_user, form.cleaned_data)

            # Redirect to success view
            return redirect('personnel')
    else:
        form = form_class()

    return render(request, 'myapp/register_personnel.html', {'form': form, 'role': selected_role})

def get_form_class_for_role(role, *args, **kwargs):
    if role == 'Driver':
        return DriverRegistrationForm
    elif role == 'Admin':
        return AdminRegistrationForm
    elif role == 'FuelingPerson':
        return FuelingPersonRegistrationForm
    elif role == 'Maintenance':
        return MaintenancePersonnelRegistrationForm
    else:
        print("You have to choose a role to register new user")

def create_related_profile(user, cleaned_data):
    print(user.role)
    if user.role == 'Driver':
        driving_license = cleaned_data.get('driving_license', None)
        print(driving_license)
        Driver.objects.create(user=user, driving_license=driving_license)
    elif user.role == 'Admin':
        Admin.objects.create(user=user)
    elif user.role == 'FuelingPerson':
        gas_station_name = cleaned_data.get('gas_station_name', None)
        FuelingPerson.objects.create(user=user, gas_station_name=gas_station_name)
    elif user.role == 'Maintenance':
        MaintenancePersonnel.objects.create(user=user)

def personnel_home(request):
    selected_role = request.GET.get('role')
    form_class = get_form_class_for_role(selected_role)

    # Assuming you have a model for each personnel type, adjust accordingly
    if selected_role == 'Driver':
        personnel_list = Driver.objects.all()
    elif selected_role == 'Admin':
        personnel_list = Admin.objects.all()
    elif selected_role == 'FuelingPerson':
        personnel_list = FuelingPerson.objects.all()
    elif selected_role == 'Maintenance':
        personnel_list = MaintenancePersonnel.objects.all()
    else:
        personnel_list = User.objects.all()  # Display all personnel

    return render(request, 'myapp/personnel.html', {'form': form_class(), 'role': selected_role, 'personnel_list': personnel_list})

def delete_personnel(request, user_id):
    user = get_object_or_404(User, id=user_id)
    user.delete()
    return redirect('personnel')  # Redirect back to the personnel page after deletion

def search_personnel(request):
    query = request.GET.get('q', '')
    personnel_data = []

    # Search in the User table based on the query
    users = User.objects.filter(first_name__icontains=query) | \
            User.objects.filter(surname__icontains=query)

    for user in users:
        user_data = {
            'id': user.id,
            'first_name': user.first_name,
            'surname': user.surname,
            'email': user.email,
            'phone_number': user.phone_number,
            'role': user.role,
            'created_at': user.created_at
        }
        # Check the user's role and get additional data from related models
        if user.role == 'Driver':
            driver = Driver.objects.get(user=user)
            user_data['vehicle'] = driver.vehicle
            user_data['driving_license'] = driver.driving_license
        elif user.role == 'FuelingPerson':
            fueling_person = FuelingPerson.objects.get(user=user)
            user_data['gas_station_name'] = fueling_person.gas_station_name
            # Add additional fields specific to FuelingPerson
        personnel_data.append(user_data)
    return render(request, 'myapp/search_personnel.html', {'personnel_data': personnel_data, 'search_query': query})

def register_vehicle(request):
    if request.method == 'POST':
        form = VehicleRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('vehicles')  # Redirect to the vehicle list page after successful registration
    else:
        form = VehicleRegistrationForm()

    return render(request, 'myapp/register_vehicle.html', {'form': form})
def vehicles(request):
    vehicles = Vehicle.objects.all()
    print(vehicles)
    return render(request, 'myapp/vehicles.html', {'vehicles': vehicles})

def assign_vehicle(request):
    if request.method == 'POST':
        form = VehicleAssignmentForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            driver_id = form.cleaned_data['driver'].id
            vehicle_id = form.cleaned_data['vehicle'].id

            # Update the Driver table to assign the vehicle to the driver
            driver = Driver.objects.get(id=driver_id)
            driver.vehicle = Vehicle.objects.get(id=vehicle_id)
            driver.save()

            return redirect('vehicles')  # Redirect to the vehicles list page
    else:
        form = VehicleAssignmentForm()

    return render(request, 'myapp/assign_vehicle.html', {'form': form})

def delete_vehicle(request, vehicle_id):
    vehicle = get_object_or_404(Vehicle, id=vehicle_id)
    vehicle.delete()
    return redirect('vehicles')  # Replace 'vehicles_list' with the URL name of your vehicle list page

import json  # Import JSON module to parse location data

def create_task(request):
    if request.method == 'POST':
        form = TaskCreationForm(request.POST)
        if form.is_valid():
            route = form.save(commit=False)

            # Process start_location and end_location from Google Maps
            start_location_data = json.loads(request.POST.get('start_location', '{}'))
            end_location_data = json.loads(request.POST.get('end_location', '{}'))

            route.start_location = f"{start_location_data.get('lat')}, {start_location_data.get('lng')}"
            route.end_location = f"{end_location_data.get('lat')}, {end_location_data.get('lng')}"

            route.save()  # Save the route with updated locations
            return redirect('home')
    else:
        form = TaskCreationForm()

    return render(request, 'myapp/create_task.html', {'form': form})

myapp/templates/myapp/about_us.html
{% extends 'myapp/base.html' %}
{% block content %}
    <p>About Us</p>
    <script>
        document.getElementById("nav-about").style.color = "#f7f7f9";
    </script>
{% endblock %}

myapp/templates/myapp/appointment.html
{% extends 'myapp/base.html' %}
{% block content %}
    <p>Make an Appointment</p>
    <script>
        document.getElementById("nav-appointment").style.color = "#f7f7f9";
    </script>
{% endblock %}

myapp/templates/myapp/assign_vehicle.html
{% extends 'myapp/base.html' %}

{% block content %}

    <h1>Assign Vehicle to Driver</h1>

    <form method="post" action="{% url 'assign_vehicle' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Assign Vehicle">
    </form>
    <script>
        document.getElementById("nav-vehicles").style.color = "#f7f7f9";
    </script>
{% endblock %}

myapp/templates/myapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VMS</title>
    <link rel="stylesheet" href="../../static/navStyle.css">
    <script>
        function showForm(role) {
            // Hide all forms
            document.getElementById('formDriver').style.display = 'none';
            document.getElementById('formAdmin').style.display = 'none';
            document.getElementById('formMaintenance').style.display = 'none';
            document.getElementById('formFuelingPerson').style.display = 'none';
    
            // Show the selected form
            document.getElementById('form' + role.charAt(0).toUpperCase() + role.slice(1)).style.display = 'block';
        }
    </script>    
</head>
<body>
    {% block header %}
    <header>
        <nav class="navbar">
            <div class="container">
                <a class="navbar-brand" href="#">VMS</a>
                <div class="navbar-nav">
                    <a class="nav-item" href="{% url 'home' %}" id="nav-home">Home</a>
                    <a class="nav-item" href="{% url 'service_page' %}" id="nav-service">Service</a> 
                    <a class="nav-item" href="{% url 'vehicles' %}" id="nav-vehicles">Vehicles</a> 
                    <a class="nav-item" href="{% url 'personnel' %}" id="nav-personnel">Personnel</a>
                    <a class="nav-item" href="{% url 'create_task' %}" id="nav-create-task">Create Task</a>
                    <a class="nav-item" href="{% url 'contacts' %}" id="nav-contacts">Contacts</a>
                    <a class="nav-item" href="{% url 'about_us' %}" id="nav-about">About Us</a>
                    <a class="nav-item" href="{% url 'make_an_appointment' %}" id="nav-appointment">Appointment</a>
                    <a class="nav-item" href="{% url 'logout' %}">Logout</a>
                </div>
                <div class="navbar-search">
                    <form method="get" action="{% url 'search_personnel' %}">
                        <input type="text" name="q" placeholder="search for staff">
                        <button type="submit">search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    {% endblock %}

    <main class="main-content">
        <!-- Content here will change depending on the template that extends base.html -->
        {% block content %}
        {% endblock content %}
    </main>

    <footer>
        <!-- Footer content here -->
    </footer>
</body>
</html>

myapp/templates/myapp/contacts.html
{% extends 'myapp/base.html' %}
{% block content %}
    <h1>Contacts</h1>
    <script>
        document.getElementById("nav-contacts").style.color = "#f7f7f9";
    </script>
{% endblock %}

myapp/templates/myapp/create_task.html
{% extends 'myapp/base.html' %}

{% block content %}
  <h2>Create Task</h2>
  <form method="post">
    {% csrf_token %}
    <p>
      <label for="id_task_name">Task Name:</label><br>
      {{ form.task_name }}
    </p>
    <p>
      <label for="id_driver_user">Driver:</label><br>
      <select name="driver_user" id="id_driver_user">
        {% for driver in form.fields.driver_user.queryset %}
          <option value="{{ driver.id }}">
            {{ driver.id }} - {{ driver.first_name }} {{ driver.surname }}
          </option>
        {% endfor %}
      </select>
    </p>
    <input type="hidden" name="start_location" id="start_location">
    <input type="hidden" name="end_location" id="end_location">
    <div id="map" style="height: 400px; width: 90%; margin-left:5%; margin-right: 5%;position: relative;">
      <!-- <div id="map-overlay" style="display: block; position: absolute; top: 0; left: 0; right: 0; bottom: 0; background-color: rgba(255,255,255,0.8); text-align: center; line-height: 400px;">
        Press CTRL + scroll to zoom
      </div> -->
    </div>
    <button type="submit">Create Task</button>
  </form>

  <script>
    let map;
    let startMarker;
    let endMarker;
    const mapOverlay = document.getElementById("map-overlay");

    function initMap() {
      map = new google.maps.Map(document.getElementById("map"), {
        center: { lat: 51.169392, lng: 71.449074 }, // Astana, Kazakhstan
        zoom: 12,
        gestureHandling: 'cooperative',
      });

      map.addListener('mousemove', function (e) {
        if (e.domEvent.ctrlKey) {
          map.setOptions({ gestureHandling: 'auto' });
        } else {
          map.setOptions({ gestureHandling: 'cooperative' });
        }
      });

      // Enable zooming only when CTRL is pressed
      map.addListener('mousemove', function (e) {
        if (e.domEvent.ctrlKey) {
          map.setOptions({ gestureHandling: 'auto' });
        } else {
          map.setOptions({ gestureHandling: 'cooperative' });
        }
      });

      map.addListener("click", (mapsMouseEvent) => {
        // Clear existing markers if both start and end are already chosen
        if (startMarker && endMarker) {
          startMarker.setMap(null);
          endMarker.setMap(null);
          startMarker = endMarker = null;
        }

        const clickedLocation = mapsMouseEvent.latLng.toJSON();
        if (!startMarker) {
          startMarker = new google.maps.Marker({
            position: clickedLocation,
            map: map,
            label: "Start",
          });
          document.getElementById('start_location').value = JSON.stringify(clickedLocation);
        } else if (!endMarker) {
          endMarker = new google.maps.Marker({
            position: clickedLocation,
            map: map,
            label: "End",
          });
          document.getElementById('end_location').value = JSON.stringify(clickedLocation);
        }
      });
    }
  </script>
  <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAq0DAj3TcXIii9h1-PfXgErLgDbRsQWEo&callback=initMap">
  </script>
{% endblock %}

myapp/templates/myapp/generic_personnel_table.html
<!-- generic_personnel_table.html -->

{% if personnel_data %}
  <table>
    <thead>
      <tr>
        <th>User ID</th>
        <th>Email</th>
        <th>First Name</th>
        <th>Surname</th>
        <th>Phone Number</th>
        <!-- Add other fields based on the role -->
        {% if selected_role == 'Driver' %}
          <th>Vehicle</th>
          <th>Driving License</th>
        {% elif selected_role == 'FuelingPerson' %}
          <th>Gas Station Name</th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
      {% for person in personnel_data %}
        <tr>
          <td>{{ person.user.id }}</td>
          <td>{{ person.user.email }}</td>
          <td>{{ person.user.first_name }}</td>
          <td>{{ person.user.surname }}</td>
          <td>{{ person.user.phone_number }}</td>
          <!-- Add other fields based on the role -->
          {% if selected_role == 'Driver' %}
            <td>{{ person.vehicle }}</td>
            <td>{{ person.driving_license }}</td>
          {% elif selected_role == 'FuelingPerson' %}
            <td>{{ person.gas_station_name }}</td>
          {% endif %}
          <td>
            <a href="{% url 'delete_personnel' person.user.id %}" onclick="return confirm('Are you sure you want to delete this user?')">Delete</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% else %}
  <p>No personnel data available.</p>
{% endif %}

myapp/templates/myapp/home.html
{% extends 'myapp/base.html' %}
{% block content %}
    <h1>Home</h1>




    <script>
        document.getElementById("nav-home").style.color = "#f7f7f9";
    </script>
{% endblock %}

myapp/templates/myapp/personnel.html
{% extends 'myapp/base.html' %}

{% block content %}
  <h1>Personnel</h1>
  <p>Select the role of employees to be displayed below</p>

  <!-- Add the dropdown menu for selecting roles -->
  <form method="get" action="{% url 'personnel' %}">
    <select name="role" onchange="this.form.submit()">
      <option value=""> Select a Role</option>
      <option value="Driver">Driver</option>
      <option value="Maintenance">Maintenance Personnel</option>
      <option value="FuelingPerson">Fueling Person</option>
    </select>
  </form>

  {% if personnel_data %}
    <!-- Display the personnel data table -->
    {% include 'myapp/generic_personnel_table.html' %}
  {% endif %}
  <a href="select_role">Register new user</a>
  <script>
    document.getElementById("nav-personnel").style.color = "#f7f7f9";
  </script>
{% endblock %}

myapp/templates/myapp/register_personnel.html
<!-- register_personnel.html -->

{% extends 'myapp/base.html' %}

{% block content %}
<h1>Register New {{ role }}</h1>

<form method="post" action="{% url 'register_personnel' %}?role={{ role }}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Register">
</form>

{% endblock %}

myapp/templates/myapp/register_vehicle.html
{% extends 'myapp/base.html' %}
{% block content %}
    <h1>Registering a new vehicle</h1>
    <form method="post" action="{% url 'register_vehicle' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register">
    </form>

    <script>
        document.getElementById("nav-vehicles").style.color = "#f7f7f9";
    </script>
{% endblock %}

myapp/templates/myapp/search_personnel.html
<!-- search_personnel.html -->

{% extends 'myapp/base.html' %}

{% block content %}
  <h1>Search Personnel</h1>

  <!-- Add your search form here if needed -->

  {% if personnel_data %}
    <p>Results for '{{ search_query }}':</p>
    <ul>
        {% for result in personnel_data %}
            <li>{{ result.first_name }} {{ result.last_name }} - {{ result.role }}</li>
            {# Add other fields as needed #}
        {% endfor %}
    </ul>
    <table> 
      <thead>
        <tr>
          <th>User ID</th>
          <th>Email</th>
          <th>First Name</th>
          <th>Surname</th>
          <th>Role</th>
          <th>Phone Number</th>
          <!-- Additional fields based on roles -->
          {% if personnel_data.0.role == 'Driver' %}
            <th>Driving License</th>
            <th>Vehicle</th>
          {% elif personnel_data.0.role == 'FuelingPerson' %}
            <th>Gas Station Name</th>
          {% endif %}
          <!-- Add other role-specific fields as needed -->
          <th>Created At</th>
        </tr>
      </thead>
      <tbody>
        {% for user in personnel_data %}
          <tr>
            <td>{{ user.id }}</td>
            <td>{{ user.email }}</td>
            <td>{{ user.first_name }}</td>
            <td>{{ user.surname }}</td>
            <td>{{ user.role }}</td>
            <td>{{ user.phone_number }}</td>
            <!-- Additional fields based on roles -->
            {% if user.role == 'Driver' %}
              <td>{{ user.driving_license }}</td>
              <td>{{ user.vehicle }}</td>
            {% elif user.role == 'FuelingPerson' %}
              <td>{{ user.gas_station_name }}</td>
            {% endif %}
            <!-- Add other role-specific fields as needed -->
            <td>{{ user.created_at }}</td>
            <!-- Add other fields from User model as needed -->
            <td>
                <a href="{% url 'delete_personnel' user.id %}" onclick="return confirm('Are you sure you want to delete this user?')">Delete</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>No search results found '{{ search_query }}'.</p>
  {% endif %}
  <script>
    document.getElementById("nav-personnel").style.color = "#f7f7f9";
  </script>
{% endblock %}

myapp/templates/myapp/vehicles.html
{% extends 'myapp/base.html' %}
{% block content %}
    <h1>Vehicles List</h1>

<!-- Display Vehicles List -->
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Make</th>
                <th>Model</th>
                <th>Year</th>
                <th>License Plate</th>
                <th>Type</th>
                <th>Sitting Capacity</th>
                <th>Status</th>
                <!-- Add other fields as needed -->
            </tr>
        </thead>
        <tbody>
            {% for vehicle in vehicles %}
                <tr>
                    <td>{{ vehicle.id }}</td>
                    <td>{{ vehicle.make }}</td>
                    <td>{{ vehicle.model }}</td>
                    <td>{{ vehicle.year }}</td>
                    <td>{{ vehicle.license_plate }}</td>
                    <td>{{ vehicle.type }}</td>
                    <td>{{ vehicle.sitting_capacity }}</td>
                    <td>{{ vehicle.status }}</td>
                    <!-- Add other fields as needed -->
                    <td>
                        <a href="{% url 'delete_vehicle' vehicle.id %}" onclick="return confirm('Are you sure you want to delete this user?')">Delete</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="register">Register new vehicle</a>
    <a href="assign">Assign a vehicle</a>
    <script>
        document.getElementById("nav-vehicles").style.color = "#f7f7f9";
    </script>
{% endblock %}